version: '3.8'

services:
  php:
    container_name: account_php
    working_dir: /var/www/symfony_docker
    build:
      context: docker
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database


  database:
    container_name: account_database
    working_dir: /var/www/symfony_docker
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: 'account'
      POSTGRES_USER: 'romakip'
      POSTGRES_PASSWORD: 'oopew32Kk32l'
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./:/var/www/symfony_docker

  nginx:
    container_name: account_nginx
    working_dir: /var/www/symfony_docker
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database